<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>CustomerService.Domain</AssemblyName>
        <RootNamespace>CustomerService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\CommunalService\CommunalService\CommunalService.Domain\CommunalService.Domain.csproj" />
    </ItemGroup>

</Project>
