<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\ToolService.Domain\ToolService.Domain.csproj" />
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.14.1" />
    <PackageReference Include="Tencent.QCloud.Cos.Sdk" Version="5.4.48" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />
  </ItemGroup>

</Project>
